// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6_yT67lNRhN8orCNDflule2QBv67q-SQ',
    appId: '1:804540985133:web:a378c457688f48ccd5ada4',
    messagingSenderId: '804540985133',
    projectId: 'rental-flutter-app-3c213',
    authDomain: 'rental-flutter-app-3c213.firebaseapp.com',
    storageBucket: 'rental-flutter-app-3c213.appspot.com',
    measurementId: 'G-7D2N8XSWZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBJqldPUJ5i8_r1KAf0keB2rbv-On0BU',
    appId: '1:804540985133:android:d1495d1ba16b46bfd5ada4',
    messagingSenderId: '804540985133',
    projectId: 'rental-flutter-app-3c213',
    storageBucket: 'rental-flutter-app-3c213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUIsZqyUb2_SfAwhAppeqYAdDt6PGjbWE',
    appId: '1:804540985133:ios:52ab96067c6717f7d5ada4',
    messagingSenderId: '804540985133',
    projectId: 'rental-flutter-app-3c213',
    storageBucket: 'rental-flutter-app-3c213.appspot.com',
    iosClientId: '804540985133-k3aacfbidc69cqqlolvcfg57li0ao4ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUIsZqyUb2_SfAwhAppeqYAdDt6PGjbWE',
    appId: '1:804540985133:ios:52ab96067c6717f7d5ada4',
    messagingSenderId: '804540985133',
    projectId: 'rental-flutter-app-3c213',
    storageBucket: 'rental-flutter-app-3c213.appspot.com',
    iosClientId: '804540985133-k3aacfbidc69cqqlolvcfg57li0ao4ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
