// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu4wu2ihqLQApxalWMO9WJ0LQkiLlfPUk',
    appId: '1:344631204709:web:00fbede5d49671a64f5f8c',
    messagingSenderId: '344631204709',
    projectId: 'vehicle-renting-app',
    authDomain: 'vehicle-renting-app.firebaseapp.com',
    storageBucket: 'vehicle-renting-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOhQ-vyGX_U5ip47kVrWsmmIqWI4HR02M',
    appId: '1:344631204709:android:be185d004462e1504f5f8c',
    messagingSenderId: '344631204709',
    projectId: 'vehicle-renting-app',
    storageBucket: 'vehicle-renting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4X9SzktkBg5TK4QaKl9FoJ0excfRoPQ',
    appId: '1:344631204709:ios:f5f90c17b35e74374f5f8c',
    messagingSenderId: '344631204709',
    projectId: 'vehicle-renting-app',
    storageBucket: 'vehicle-renting-app.appspot.com',
    iosClientId: '344631204709-1lrprd4l18der94jm52jda7pgr06598e.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD4X9SzktkBg5TK4QaKl9FoJ0excfRoPQ',
    appId: '1:344631204709:ios:f5f90c17b35e74374f5f8c',
    messagingSenderId: '344631204709',
    projectId: 'vehicle-renting-app',
    storageBucket: 'vehicle-renting-app.appspot.com',
    iosClientId: '344631204709-1lrprd4l18der94jm52jda7pgr06598e.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
